# Use Node.js LTS version as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Build-time variables
ARG PORT
ARG NODE_ENV
ARG BASE_URL
ARG FRONT_URL
ARG DB_URL
ARG ALLOW_ORIGIN
ARG MAILGUN_USER
ARG MAILGUN_PASSWORD
ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_S3_BUCKET_NAME
ARG AWS_S3_BUCKET
ARG AWS_SES_EMAIL_FROM
ARG S3_IMAGE_URL
ARG CURRENCY_CONVERT_API_KEY
ARG REDIS_URL
ARG TYPE
ARG PROJECT_ID
ARG PRIVATE_KEY_ID
ARG PRIVATE_KEY
ARG CLIENT_EMAIL
ARG CLIENT_ID
ARG AUTH_URI
ARG TOKEN_URI
ARG AUTH_PROVIDER_X509_CERT_URL
ARG CLIENT_X509_CERT_URL
ARG UNIVERSE_DOMAIN

# Define environment variables
ENV PORT=${PORT}
ENV NODE_ENV=${NODE_ENV}
ENV BASE_URL=${BASE_URL}
ENV FRONT_URL=${FRONT_URL}
ENV DB_URL=${DB_URL}
ENV ALLOW_ORIGIN=${ALLOW_ORIGIN}
ENV MAILGUN_USER=${MAILGUN_USER}
ENV MAILGUN_PASSWORD=${MAILGUN_PASSWORD}
ENV EMAIL_HOST=${EMAIL_HOST}
ENV EMAIL_PORT=${EMAIL_PORT}
ENV EMAIL_HOST_USER=${EMAIL_HOST_USER}
ENV EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_SES_EMAIL_FROM=${AWS_SES_EMAIL_FROM}
ENV S3_IMAGE_URL=${S3_IMAGE_URL}
ENV CURRENCY_CONVERT_API_KEY=${CURRENCY_CONVERT_API_KEY}
ENV REDIS_URL=${REDIS_URL}
ENV TZ=Asia/Kolkata
ENV TYPE=${TYPE}
ENV PROJECT_ID=${PROJECT_ID}
ENV PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
ENV PRIVATE_KEY=${PRIVATE_KEY}
ENV CLIENT_EMAIL=${CLIENT_EMAIL}
ENV CLIENT_ID=${CLIENT_ID}
ENV AUTH_URI=${AUTH_URI}
ENV TOKEN_URI=${TOKEN_URI}
ENV AUTH_PROVIDER_X509_CERT_URL=${AUTH_PROVIDER_X509_CERT_URL}
ENV CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL}
ENV UNIVERSE_DOMAIN=${UNIVERSE_DOMAIN}

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Expose the port for the Node.js application
EXPOSE ${PORT}

# Start the Node.js application
CMD ["npm", "start"]
